// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chambre.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ChambreResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChambreResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Chambre chambre = 1;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   * @return The chambre.
   */
  com.hotel.tp_reservation_grpc.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ChambreOrBuilder getChambreOrBuilder();
}
