// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chambre.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ChambreListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChambreListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  java.util.List<com.hotel.tp_reservation_grpc.stubs.Chambre> 
      getChambresList();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.Chambre getChambres(int index);
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  int getChambresCount();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  java.util.List<? extends com.hotel.tp_reservation_grpc.stubs.ChambreOrBuilder> 
      getChambresOrBuilderList();
  /**
   * <code>repeated .Chambre chambres = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ChambreOrBuilder getChambresOrBuilder(
      int index);
}
