// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chambre.proto

package com.hotel.tp_reservation_grpc.stubs;

public final class ChambreProto {
  private ChambreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChambreIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChambreIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateChambreRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateChambreRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChambreResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChambreResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChambreListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChambreListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchambre.proto\"Z\n\007Chambre\022\n\n\002id\030\001 \001(\003\022!" +
      "\n\013typeChambre\030\002 \001(\0162\014.TypeChambre\022\014\n\004pri" +
      "x\030\003 \001(\001\022\022\n\ndisponible\030\004 \001(\010\"+\n\016ChambreRe" +
      "quest\022\031\n\007chambre\030\001 \001(\0132\010.Chambre\"\036\n\020Cham" +
      "breIdRequest\022\n\n\002id\030\001 \001(\003\"=\n\024UpdateChambr" +
      "eRequest\022\n\n\002id\030\001 \001(\003\022\031\n\007chambre\030\002 \001(\0132\010." +
      "Chambre\",\n\017ChambreResponse\022\031\n\007chambre\030\001 " +
      "\001(\0132\010.Chambre\"1\n\023ChambreListResponse\022\032\n\010" +
      "chambres\030\001 \003(\0132\010.Chambre\"\016\n\014EmptyRequest" +
      "\"\017\n\rEmptyResponse*%\n\013TypeChambre\022\n\n\006SIMP" +
      "LE\020\000\022\n\n\006DOUBLE\020\0012\240\002\n\016ChambreService\0222\n\rC" +
      "reateChambre\022\017.ChambreRequest\032\020.ChambreR" +
      "esponse\0225\n\016GetChambreById\022\021.ChambreIdReq" +
      "uest\032\020.ChambreResponse\0225\n\016GetAllChambres" +
      "\022\r.EmptyRequest\032\024.ChambreListResponse\0228\n" +
      "\rUpdateChambre\022\025.UpdateChambreRequest\032\020." +
      "ChambreResponse\0222\n\rDeleteChambre\022\021.Chamb" +
      "reIdRequest\032\016.EmptyResponseB5\n#com.hotel" +
      ".tp_reservation_grpc.stubsB\014ChambreProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "TypeChambre", "Prix", "Disponible", });
    internal_static_ChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChambreRequest_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_ChambreIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ChambreIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChambreIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateChambreRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateChambreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateChambreRequest_descriptor,
        new java.lang.String[] { "Id", "Chambre", });
    internal_static_ChambreResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ChambreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChambreResponse_descriptor,
        new java.lang.String[] { "Chambre", });
    internal_static_ChambreListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ChambreListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChambreListResponse_descriptor,
        new java.lang.String[] { "Chambres", });
    internal_static_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_EmptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
