// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chambre.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ChambreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chambre)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.TypeChambre typeChambre = 2;</code>
   * @return The enum numeric value on the wire for typeChambre.
   */
  int getTypeChambreValue();
  /**
   * <code>.TypeChambre typeChambre = 2;</code>
   * @return The typeChambre.
   */
  com.hotel.tp_reservation_grpc.stubs.TypeChambre getTypeChambre();

  /**
   * <code>double prix = 3;</code>
   * @return The prix.
   */
  double getPrix();

  /**
   * <code>bool disponible = 4;</code>
   * @return The disponible.
   */
  boolean getDisponible();
}
