// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 1;</code>
   * @return The client.
   */
  com.hotel.tp_reservation_grpc.stubs.Client getClient();
  /**
   * <code>.Client client = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ClientOrBuilder getClientOrBuilder();
}
