// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.hotel.tp_reservation_grpc.stubs;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\"S\n\006Client\022\n\n\002id\030\001 \001(\003\022\013\n\003" +
      "nom\030\002 \001(\t\022\016\n\006prenom\030\003 \001(\t\022\r\n\005email\030\004 \001(\t" +
      "\022\021\n\ttelephone\030\005 \001(\t\"(\n\rClientRequest\022\027\n\006" +
      "client\030\001 \001(\0132\007.Client\"\035\n\017ClientIdRequest" +
      "\022\n\n\002id\030\001 \001(\003\":\n\023UpdateClientRequest\022\n\n\002i" +
      "d\030\001 \001(\003\022\027\n\006client\030\002 \001(\0132\007.Client\")\n\016Clie" +
      "ntResponse\022\027\n\006client\030\001 \001(\0132\007.Client\".\n\022C" +
      "lientListResponse\022\030\n\007clients\030\001 \003(\0132\007.Cli" +
      "ent\"\016\n\014EmptyRequest\"\017\n\rEmptyResponse2\222\002\n" +
      "\rClientService\022/\n\014CreateClient\022\016.ClientR" +
      "equest\032\017.ClientResponse\0222\n\rGetClientById" +
      "\022\020.ClientIdRequest\032\017.ClientResponse\0223\n\rG" +
      "etAllClients\022\r.EmptyRequest\032\023.ClientList" +
      "Response\0225\n\014UpdateClient\022\024.UpdateClientR" +
      "equest\032\017.ClientResponse\0220\n\014DeleteClient\022" +
      "\020.ClientIdRequest\032\016.EmptyResponseB4\n#com" +
      ".hotel.tp_reservation_grpc.stubsB\013Client" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_ClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientRequest_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_ClientIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateClientRequest_descriptor,
        new java.lang.String[] { "Id", "Client", });
    internal_static_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientResponse_descriptor,
        new java.lang.String[] { "Client", });
    internal_static_ClientListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ClientListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientListResponse_descriptor,
        new java.lang.String[] { "Clients", });
    internal_static_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_EmptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
