// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ClientListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Client clients = 1;</code>
   */
  java.util.List<com.hotel.tp_reservation_grpc.stubs.Client> 
      getClientsList();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.Client getClients(int index);
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  java.util.List<? extends com.hotel.tp_reservation_grpc.stubs.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .Client clients = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ClientOrBuilder getClientsOrBuilder(
      int index);
}
