// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilisateur.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface EmptyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmptyResponse)
    com.google.protobuf.MessageOrBuilder {
}
