// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.hotel.tp_reservation_grpc.stubs;

public final class ReservationProto {
  private ReservationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\"R\n\013Reservation\022\n\n\002id" +
      "\030\001 \001(\003\022\021\n\tdateDebut\030\002 \001(\t\022\017\n\007dateFin\030\003 \001" +
      "(\t\022\023\n\013preferences\030\004 \001(\t\"7\n\022ReservationRe" +
      "quest\022!\n\013reservation\030\001 \001(\0132\014.Reservation" +
      "\"\"\n\024ReservationIdRequest\022\n\n\002id\030\001 \001(\003\"I\n\030" +
      "UpdateReservationRequest\022\n\n\002id\030\001 \001(\003\022!\n\013" +
      "reservation\030\002 \001(\0132\014.Reservation\"8\n\023Reser" +
      "vationResponse\022!\n\013reservation\030\001 \001(\0132\014.Re" +
      "servation\"=\n\027ReservationListResponse\022\"\n\014" +
      "reservations\030\001 \003(\0132\014.Reservation\"\016\n\014Empt" +
      "yRequest\"\017\n\rEmptyResponse2\330\002\n\022Reservatio" +
      "nService\022>\n\021CreateReservation\022\023.Reservat" +
      "ionRequest\032\024.ReservationResponse\022A\n\022GetR" +
      "eservationById\022\025.ReservationIdRequest\032\024." +
      "ReservationResponse\022=\n\022GetAllReservation" +
      "s\022\r.EmptyRequest\032\030.ReservationListRespon" +
      "se\022D\n\021UpdateReservation\022\031.UpdateReservat" +
      "ionRequest\032\024.ReservationResponse\022:\n\021Dele" +
      "teReservation\022\025.ReservationIdRequest\032\016.E" +
      "mptyResponseB9\n#com.hotel.tp_reservation" +
      "_grpc.stubsB\020ReservationProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "DateDebut", "DateFin", "Preferences", });
    internal_static_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_ReservationIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReservationIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "Reservation", });
    internal_static_ReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_ReservationListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ReservationListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationListResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_EmptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
