// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ReservationIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
