// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface ReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  com.hotel.tp_reservation_grpc.stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ReservationOrBuilder getReservationOrBuilder();
}
