// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface UpdateClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.Client client = 2;</code>
   * @return The client.
   */
  com.hotel.tp_reservation_grpc.stubs.Client getClient();
  /**
   * <code>.Client client = 2;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ClientOrBuilder getClientOrBuilder();
}
