// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chambre.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface UpdateChambreRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateChambreRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.Chambre chambre = 2;</code>
   * @return Whether the chambre field is set.
   */
  boolean hasChambre();
  /**
   * <code>.Chambre chambre = 2;</code>
   * @return The chambre.
   */
  com.hotel.tp_reservation_grpc.stubs.Chambre getChambre();
  /**
   * <code>.Chambre chambre = 2;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.ChambreOrBuilder getChambreOrBuilder();
}
