// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilisateur.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface UtilisateurOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Utilisateur)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string nom = 2;</code>
   * @return The nom.
   */
  java.lang.String getNom();
  /**
   * <code>string nom = 2;</code>
   * @return The bytes for nom.
   */
  com.google.protobuf.ByteString
      getNomBytes();

  /**
   * <code>string motDePasse = 3;</code>
   * @return The motDePasse.
   */
  java.lang.String getMotDePasse();
  /**
   * <code>string motDePasse = 3;</code>
   * @return The bytes for motDePasse.
   */
  com.google.protobuf.ByteString
      getMotDePasseBytes();

  /**
   * <code>.Role role = 4;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.Role role = 4;</code>
   * @return The role.
   */
  com.hotel.tp_reservation_grpc.stubs.Role getRole();
}
