// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilisateur.proto

package com.hotel.tp_reservation_grpc.stubs;

public final class UtilisateurProto {
  private UtilisateurProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Utilisateur_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Utilisateur_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UtilisateurRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UtilisateurRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UtilisateurIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UtilisateurIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateUtilisateurRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateUtilisateurRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UtilisateurResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UtilisateurResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UtilisateurListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UtilisateurListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmptyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021utilisateur.proto\"O\n\013Utilisateur\022\n\n\002id" +
      "\030\001 \001(\003\022\013\n\003nom\030\002 \001(\t\022\022\n\nmotDePasse\030\003 \001(\t\022" +
      "\023\n\004role\030\004 \001(\0162\005.Role\"7\n\022UtilisateurReque" +
      "st\022!\n\013utilisateur\030\001 \001(\0132\014.Utilisateur\"\"\n" +
      "\024UtilisateurIdRequest\022\n\n\002id\030\001 \001(\003\"I\n\030Upd" +
      "ateUtilisateurRequest\022\n\n\002id\030\001 \001(\003\022!\n\013uti" +
      "lisateur\030\002 \001(\0132\014.Utilisateur\"8\n\023Utilisat" +
      "eurResponse\022!\n\013utilisateur\030\001 \001(\0132\014.Utili" +
      "sateur\"=\n\027UtilisateurListResponse\022\"\n\014uti" +
      "lisateurs\030\001 \003(\0132\014.Utilisateur\"\016\n\014EmptyRe" +
      "quest\"\017\n\rEmptyResponse*\033\n\004Role\022\010\n\004USER\020\000" +
      "\022\t\n\005ADMIN\020\0012\330\002\n\022UtilisateurService\022>\n\021Cr" +
      "eateUtilisateur\022\023.UtilisateurRequest\032\024.U" +
      "tilisateurResponse\022A\n\022GetUtilisateurById" +
      "\022\025.UtilisateurIdRequest\032\024.UtilisateurRes" +
      "ponse\022=\n\022GetAllUtilisateurs\022\r.EmptyReque" +
      "st\032\030.UtilisateurListResponse\022D\n\021UpdateUt" +
      "ilisateur\022\031.UpdateUtilisateurRequest\032\024.U" +
      "tilisateurResponse\022:\n\021DeleteUtilisateur\022" +
      "\025.UtilisateurIdRequest\032\016.EmptyResponseB9" +
      "\n#com.hotel.tp_reservation_grpc.stubsB\020U" +
      "tilisateurProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Utilisateur_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Utilisateur_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Utilisateur_descriptor,
        new java.lang.String[] { "Id", "Nom", "MotDePasse", "Role", });
    internal_static_UtilisateurRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UtilisateurRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UtilisateurRequest_descriptor,
        new java.lang.String[] { "Utilisateur", });
    internal_static_UtilisateurIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UtilisateurIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UtilisateurIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateUtilisateurRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateUtilisateurRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateUtilisateurRequest_descriptor,
        new java.lang.String[] { "Id", "Utilisateur", });
    internal_static_UtilisateurResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UtilisateurResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UtilisateurResponse_descriptor,
        new java.lang.String[] { "Utilisateur", });
    internal_static_UtilisateurListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UtilisateurListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UtilisateurListResponse_descriptor,
        new java.lang.String[] { "Utilisateurs", });
    internal_static_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_EmptyResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EmptyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmptyResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
