// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilisateur.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface UtilisateurListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UtilisateurListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  java.util.List<com.hotel.tp_reservation_grpc.stubs.Utilisateur> 
      getUtilisateursList();
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.Utilisateur getUtilisateurs(int index);
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  int getUtilisateursCount();
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  java.util.List<? extends com.hotel.tp_reservation_grpc.stubs.UtilisateurOrBuilder> 
      getUtilisateursOrBuilderList();
  /**
   * <code>repeated .Utilisateur utilisateurs = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.UtilisateurOrBuilder getUtilisateursOrBuilder(
      int index);
}
