// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilisateur.proto

package com.hotel.tp_reservation_grpc.stubs;

public interface UtilisateurResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UtilisateurResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Utilisateur utilisateur = 1;</code>
   * @return Whether the utilisateur field is set.
   */
  boolean hasUtilisateur();
  /**
   * <code>.Utilisateur utilisateur = 1;</code>
   * @return The utilisateur.
   */
  com.hotel.tp_reservation_grpc.stubs.Utilisateur getUtilisateur();
  /**
   * <code>.Utilisateur utilisateur = 1;</code>
   */
  com.hotel.tp_reservation_grpc.stubs.UtilisateurOrBuilder getUtilisateurOrBuilder();
}
